version: '3'

services:
  biotools:
    build:
      context: ./docker
      dockerfile: Dockerfile.biotools
    volumes:
      - .:/work

  jupyter:
    build:
      context: ./docker
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    profiles:
      - jupyter
