version: '3'

services:
  jupyter:
    build:
      context: ./docker
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''

  biotools:
    build:
      context: ./docker
      dockerfile: Dockerfile.biotools
    volumes:
      - .:/work
